import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, scrypt as scryptCb, timingSafeEqual, createHmac } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCb), root=dirname(fileURLToPath(import.meta.url)), dataDir=join(root,'data');
await mkdir(dataDir,{recursive:true});
try{const envFile=await readFile(join(root,'.env'),'utf8');for(const line of envFile.split(/\r?\n/)){const p=line.indexOf('=');if(p>0&&!process.env[line.slice(0,p).trim()])process.env[line.slice(0,p).trim()]=line.slice(p+1).trim()}}catch{}
const files={users:join(dataDir,'users.json'),auctions:join(dataDir,'auctions.json'),orders:join(dataDir,'orders.json')};
const seed=[
{id:1,title:'Seiko 5 Sports Automatic',cat:'Watches',loc:'Makati City, Metro Manila',price:6200,bids:14,end:10700,img:'photo-1523170335258-f5ed11844a49',badge:'Verified seller',step:200},
{id:2,title:'Vintage Polaroid SX-70',cat:'Collectibles',loc:'Quezon City, Metro Manila',price:3850,bids:9,end:22100,img:'photo-1516035069371-29a1b244cc32',badge:'Vintage find',step:100},
{id:3,title:'Handwoven Bicol Abaca Tote',cat:'Fashion',loc:'Legazpi City, Albay',price:1250,bids:6,end:47300,img:'photo-1590874889-7c6c7c1b9a5c',badge:'Locally made',step:50},
{id:4,title:'Sony WH-1000XM4 Headphones',cat:'Tech',loc:'Cebu City, Cebu',price:7400,bids:18,end:83600,img:'photo-1546435770-a3e426bf472b',badge:'Verified seller',step:200},
{id:5,title:'Kalinga Handwoven Wall Textile',cat:'Home & Art',loc:'Baguio City, Benguet',price:2900,bids:11,end:143000,img:'photo-1577083552431-6e5fd01aa342',badge:'Artisan made',step:100},
{id:6,title:'Canon AE-1 35mm Film Camera',cat:'Tech',loc:'Davao City, Davao del Sur',price:5100,bids:7,end:194000,img:'photo-1516035069371-29a1b244cc32',badge:'Tested & working',step:200},
{id:7,title:'Nike Dunk Low Panda · US 8',cat:'Fashion',loc:'Pasig City, Metro Manila',price:4600,bids:12,end:268000,img:'photo-1542291026-7eec264c27ff',badge:'Authenticated',step:200},
{id:8,title:'Brass Capiz Table Lamp',cat:'Home & Art',loc:'Iloilo City, Iloilo',price:1800,bids:4,end:312000,img:'photo-1507473885765-e6ed057f782c',badge:'One of a kind',step:100},
];
async function load(key,fallback){if(!existsSync(files[key])){await save(key,fallback);return fallback}try{return JSON.parse(await readFile(files[key],'utf8'))}catch{return fallback}}
async function save(key,value){await writeFile(files[key],JSON.stringify(value,null,2),'utf8')}
let users=await load('users',[]), auctions=await load('auctions',seed), orders=await load('orders',[]), sessions=new Map();
for (const a of auctions) if (!a.endAt) a.endAt=Date.now()+Math.max(60,Number(a.end)||3600)*1000;
await save('auctions',auctions);
const sessionCookie=(token)=>`bb_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`;
const send=(res,status,data,headers={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(data))};
async function body(req){let s='';for await(const c of req)s+=c;if(s.length>1e6)throw Error('Request too large');return s?JSON.parse(s):{}}
function currentUser(req){let token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('bb_session='))?.slice(11);return sessions.get(token)||null}
function safeUser(u){return {id:u.id,name:u.name,email:u.email}}
function validString(s,min,max){return typeof s==='string'&&s.trim().length>=min&&s.trim().length<=max}
const server=http.createServer(async(req,res)=>{try{
const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/healthz')return send(res,200,{ok:true});
if(req.method==='GET'&&url.pathname==='/api/auctions'){let u=currentUser(req);return send(res,200,auctions.map(a=>({...a,end:Math.max(0,Math.ceil((a.endAt-Date.now())/1000)),isWinner:!!u&&a.lastBidder===u.id,paid:orders.some(o=>o.auctionId===a.id&&o.userId===u?.id&&o.status==='paid')})))}
if(req.method==='GET'&&url.pathname==='/api/me'){let u=currentUser(req);return send(res,200,{user:u?safeUser(u):null})}
if(req.method==='POST'&&url.pathname==='/api/signup'){
 const b=await body(req),email=String(b.email||'').trim().toLowerCase();if(!validString(b.name,2,60)||!/^\S+@\S+\.\S+$/.test(email)||String(b.password||'').length<8)return send(res,400,{error:'Enter a name, valid email, and password with at least 8 characters.'});if(users.some(u=>u.email===email))return send(res,409,{error:'An account with that email already exists.'});
 const salt=randomBytes(16).toString('hex'),hash=(await scrypt(String(b.password),salt,64)).toString('hex'),u={id:randomBytes(12).toString('hex'),name:b.name.trim(),email,salt,hash};users.push(u);await save('users',users);let token=randomBytes(32).toString('hex');sessions.set(token,u);return send(res,201,{user:safeUser(u)},{'set-cookie':sessionCookie(token)});
}
if(req.method==='POST'&&url.pathname==='/api/login'){
 const b=await body(req),email=String(b.email||'').trim().toLowerCase(),u=users.find(x=>x.email===email);if(!u)return send(res,401,{error:'Email or password is incorrect.'});const h=await scrypt(String(b.password||''),u.salt,64);if(!timingSafeEqual(h,Buffer.from(u.hash,'hex')))return send(res,401,{error:'Email or password is incorrect.'});let token=randomBytes(32).toString('hex');sessions.set(token,u);return send(res,200,{user:safeUser(u)},{'set-cookie':sessionCookie(token)});
}
if(req.method==='POST'&&url.pathname==='/api/logout'){let token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('bb_session='))?.slice(11);if(token)sessions.delete(token);return send(res,200,{ok:true},{'set-cookie':'bb_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
const bidMatch=url.pathname.match(/^\/api\/auctions\/(\d+)\/bids$/);if(req.method==='POST'&&bidMatch){let u=currentUser(req);if(!u)return send(res,401,{error:'Sign in to place a bid.'});let a=auctions.find(x=>x.id===Number(bidMatch[1]));if(!a)return send(res,404,{error:'Auction not found.'});if(a.endAt<=Date.now())return send(res,409,{error:'This auction has ended.'});let b=await body(req),minimum=a.price+a.step;if(!Number.isFinite(b.amount)||b.amount<minimum)return send(res,400,{error:`Minimum next bid is ₱${minimum.toLocaleString('en-PH')}.`});a.price=Math.round(b.amount);a.bids++;a.lastBidder=u.id;await save('auctions',auctions);return send(res,201,{auction:a})}
const checkoutMatch=url.pathname.match(/^\/api\/auctions\/(\d+)\/checkout$/);if(req.method==='POST'&&checkoutMatch){let u=currentUser(req);if(!u)return send(res,401,{error:'Sign in to continue.'});if(!process.env.PAYMONGO_SECRET_KEY)return send(res,503,{error:'Payment is not configured yet. Add PAYMONGO_SECRET_KEY after creating your PayMongo account.'});let a=auctions.find(x=>x.id===Number(checkoutMatch[1]));if(!a)return send(res,404,{error:'Auction not found.'});if(a.endAt>Date.now())return send(res,409,{error:'This auction is still live.'});if(a.lastBidder!==u.id)return send(res,403,{error:'Only the winning bidder can pay for this auction.'});if(orders.some(o=>o.auctionId===a.id&&o.userId===u.id&&o.status==='paid'))return send(res,409,{error:'This auction is already marked paid.'});let existing=orders.find(o=>o.auctionId===a.id&&o.userId===u.id&&o.status==='pending');if(existing?.checkoutUrl)return send(res,200,{checkoutUrl:existing.checkoutUrl});let ref=`BB-${a.id}-${randomBytes(6).toString('hex').toUpperCase()}`,base=process.env.PUBLIC_URL||`${req.headers['x-forwarded-proto']||'http'}://${req.headers['x-forwarded-host']||req.headers.host}`,amount=Math.round(a.price*100);let response=await fetch('https://api.paymongo.com/v2/checkout_sessions',{method:'POST',headers:{authorization:'Basic '+Buffer.from(`${process.env.PAYMONGO_SECRET_KEY}:`).toString('base64'),'content-type':'application/json'},body:JSON.stringify({data:{attributes:{line_items:[{name:a.title,amount,currency:'PHP',quantity:1}],payment_method_types:['card','gcash','qrph'],success_url:`${base}/?payment=success&ref=${ref}`,cancel_url:`${base}/?payment=cancelled&ref=${ref}`,reference_number:ref,description:`Winning bid for BIDBAYAN auction ${a.id}`}}})});let payload=await response.json();if(!response.ok)return send(res,502,{error:payload.errors?.[0]?.detail||'PayMongo could not create checkout.'});let cs=payload.data;orders=orders.filter(o=>!(o.auctionId===a.id&&o.userId===u.id&&o.status==='pending'));orders.push({reference:ref,auctionId:a.id,userId:u.id,amount:a.price,status:'pending',checkoutSessionId:cs.id,checkoutUrl:cs.attributes.checkout_url,createdAt:Date.now()});await save('orders',orders);return send(res,201,{checkoutUrl:cs.attributes.checkout_url})}
if(req.method==='POST'&&url.pathname==='/webhooks/paymongo'){let raw='';for await(const c of req)raw+=c;if(!process.env.PAYMONGO_WEBHOOK_SECRET)return send(res,503,{error:'Webhook secret is not configured'});let sig=(req.headers['paymongo-signature']||'').split(',').map(x=>x.trim().split('=')),parts=Object.fromEntries(sig),time=Number(parts.t);if(!Number.isFinite(time)||Math.abs(Date.now()/1000-time)>300)return send(res,401,{error:'Expired signature'});let candidates=['te','li'].filter(k=>parts[k]),verified=candidates.some(k=>{let expected=createHmac('sha256',process.env.PAYMONGO_WEBHOOK_SECRET).update(`${parts.t}.${raw}`).digest('hex'),p=parts[k]||'';return p.length===expected.length&&timingSafeEqual(Buffer.from(p),Buffer.from(expected))});if(!verified)return send(res,401,{error:'Invalid signature'});let event=JSON.parse(raw).data?.attributes||{},type=event.type,cs=event.data;if(type==='checkout_session.payment.paid'&&cs){let attrs=cs.attributes||{},order=orders.find(o=>o.reference===attrs.reference_number&&o.checkoutSessionId===cs.id);if(order&&order.status!=='paid'&&attrs.line_items?.[0]?.amount===order.amount*100&&attrs.line_items?.[0]?.currency==='PHP'){order.status='paid';order.paidAt=Date.now();order.paymentId=attrs.payments?.[0]?.id||attrs.payment_intent?.id||null;await save('orders',orders)}}return send(res,200,{received:true})}
if(req.method==='POST'&&url.pathname==='/api/auctions'){let u=currentUser(req);if(!u)return send(res,401,{error:'Sign in to list an item.'});let b=await body(req);if(!validString(b.title,5,90)||!validString(b.cat,2,40)||!validString(b.loc,3,100)||!Number.isFinite(b.price)||b.price<50)return send(res,400,{error:'Add a title, category, location, and starting price of at least ₱50.'});let duration=Math.max(1,Math.min(14,Number(b.days)||3));let a={id:Math.max(...auctions.map(x=>x.id),0)+1,title:b.title.trim(),cat:b.cat,loc:b.loc.trim(),price:Math.round(b.price),bids:0,endAt:Date.now()+duration*86400000,end:duration*86400,img:'photo-1542291026-7eec264c27ff',badge:'New listing',step:50,seller:u.id};auctions.unshift(a);await save('auctions',auctions);return send(res,201,{auction:a})}
if(req.method==='GET'&&url.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(await readFile(join(root,'index.html')))}
return send(res,404,{error:'Not found'});
}catch(e){console.error(e);send(res,500,{error:'Server error. Please try again.'})}});
const port=Number(process.env.PORT)||4173;server.listen(port,process.env.HOST||'0.0.0.0',()=>console.log(`BIDBAYAN is running on port ${port}`));



